name: publish

on:
  push:
    tags:
      - '*'
env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout Submodule
      run: git submodule update --init --recursive
    - name: Login to crates.io
      run: cargo login ${{ secrets.CARGO_LOGIN }}
    - name: Publish to crates.io
      run:  cargo publish